//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 12:16:34 PM IST 
//


package ieco.internal.middleware.domain.request.sms;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ieco.integration.sms.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ieco.integration.sms.request
     * 
     */
    public ObjectFactory objectFactory() {
        return new ObjectFactory();
    }

    /**
     * Create an instance of {@link SMSAPIReq }
     * 
     */
    public SMSAPIReq createSMSAPIReq() {
        return new SMSAPIReq();
    }

    /**
     * Create an instance of {@link SMSAPIReq.Req }
     * 
     */
    public SMSAPIReq.Req createSMSAPIReqReq() {
        return new SMSAPIReq.Req();
    }

    /**
     * Create an instance of {@link SMSAPIReq.Req.Messages }
     * 
     */
    public SMSAPIReq.Req.Messages createSMSAPIReqReqMessages() {
        return new SMSAPIReq.Req.Messages();
    }

    /**
     * Create an instance of {@link SMSAPIReq.Req.Messages.Message }
     * 
     */
    public SMSAPIReq.Req.Messages.Message createSMSAPIReqReqMessagesMessage() {
        return new SMSAPIReq.Req.Messages.Message();
    }

    /**
     * Create an instance of {@link SMSAPIReq.Req.Messages.Message.Destinations }
     * 
     */
    public SMSAPIReq.Req.Messages.Message.Destinations createSMSAPIReqReqMessagesMessageDestinations() {
        return new SMSAPIReq.Req.Messages.Message.Destinations();
    }

    /**
     * Create an instance of {@link SMSAPIReq.Header }
     * 
     */
    public SMSAPIReq.Header createSMSAPIReqHeader() {
        return new SMSAPIReq.Header();
    }

    /**
     * Create an instance of {@link SMSAPIReq.Req.Messages.Message.Destinations.Destination }
     * 
     */
    public SMSAPIReq.Req.Messages.Message.Destinations.Destination createSMSAPIReqReqMessagesMessageDestinationsDestination() {
        return new SMSAPIReq.Req.Messages.Message.Destinations.Destination();
    }

}
