//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 12:16:38 PM IST 
//


package ieco.internal.middleware.domain.response.sms;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ieco.integration.sms.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ieco.integration.sms.response
     * 
     */
    public ObjectFactory objectFactory() {
        return new ObjectFactory();
    }

    /**
     * Create an instance of {@link SMSAPIRes }
     * 
     */
    public SMSAPIRes createSMSAPIRes() {
        return new SMSAPIRes();
    }

    /**
     * Create an instance of {@link SMSAPIRes.Header }
     * 
     */
    public SMSAPIRes.Header createSMSAPIResHeader() {
        return new SMSAPIRes.Header();
    }

    /**
     * Create an instance of {@link SMSAPIRes.Res }
     * 
     */
    public SMSAPIRes.Res createSMSAPIResRes() {
        return new SMSAPIRes.Res();
    }

}
