//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 12:16:38 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kotak.com/schemas/SMSAPIRes/SMSAPIRes.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ieco.internal.middleware.domain.response.sms;
