//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 12:16:38 PM IST 
//


package ieco.internal.middleware.domain.response;


import lombok.ToString;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SrcAppCd" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RequestID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Res" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="toNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="MsgTxt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="AcceptanceTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Certificate")
@ToString
public class DigiLockerPanRes {
	
	@XmlAttribute
	private String number;

	@XmlElement(name = "IssuedTo", required = true)
   private IssuedTo issuedTo;
	/**
	 * @return the number
	 */
	public String getNumber() {
		return number;
	}



	/**
	 * @param number the number to set
	 */
	public void setNumber(String number) {
		this.number = number;
	}



	/**
	 * @return the issuedTo
	 */
	public IssuedTo getIssuedTo() {
		return issuedTo;
	}



	/**
	 * @param issuedTo the issuedTo to set
	 */
	public void setIssuedTo(IssuedTo issuedTo) {
		this.issuedTo = issuedTo;
	}



	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SrcAppCd" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RequestID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
       
        "person"
    })
    @ToString
    public static class IssuedTo {

    	
    	@XmlElement(name = "Person", required = true)   
    	private Person person;
        
      
		/**
		 * @return the person
		 */
		public Person getPerson() {
			return person;
		}


		/**
		 * @param person the person to set
		 */
		public void setPerson(Person person) {
			this.person = person;
		}


		@XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
		@ToString
        public static class Person {
        	
			@XmlAttribute
        	private String name;
			
			@XmlAttribute
        	private String dob;
			
			@XmlAttribute
        	private String gender;

			/**
			 * @return the name
			 */
			public String getName() {
				return name;
			}

			/**
			 * @param name the name to set
			 */
			public void setName(String name) {
				this.name = name;
			}

			/**
			 * @return the dob
			 */
			public String getDob() {
				return dob;
			}

			/**
			 * @param dob the dob to set
			 */
			public void setDob(String dob) {
				this.dob = dob;
			}

			/**
			 * @return the gender
			 */
			public String getGender() {
				return gender;
			}

			/**
			 * @param gender the gender to set
			 */
			public void setGender(String gender) {
				this.gender = gender;
			}
			

        }

    }



}
